### ISSUE TITLE
Formato fecha / hora

### ISSUE THREAD

**Issue by ghost** [ProyectoW2W/Serflix-Android#10]

**Comment by ghost** [comment]
Al recoger la fecha y la hora del pickerview se esta recogiendo en dos variables diferentes. Mirar como se puede juntar las dos fechas en una sola variable de tipo Date @larrybets

**Comment by larrybets** [comment]
Voy  comentar la linea de código que he hecho, de esta manera podremos probarlo cuando se pueda, y en caso de no funcionar podemos volver a usar el código que ya teníamos.
Saludos amiwitos
