### ISSUE TITLE
Obtener coordenadas telefono

### ISSUE THREAD

**Issue by ghost** [ProyectoW2W/Serflix-Android#7]

**Comment by ghost** [comment]
http://www.ssaurel.com/blog/how-to-get-user-current-location-with-gps-or-network/

**Comment by ghost** [comment]
Quedan por hacer 3 cosas:
- Localizar por red
- Localizar al iniciar la aplicacion
- Incluir un boton al final del textfield de localizacion en la request activity.

@victoramador @serek9

**Comment by serek9** [comment]
#11 el error 500 fue culpa del emulador, no da.
